name: Access Control

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  access-check:
    runs-on: ubuntu-latest

    steps:
      - name: Check if repository is forked and starred
        id: check-access
        run: |
          if [[ $(curl -s -o /dev/null -w "%{http_code}" https://api.github.com/repos/${{ github.repository }}/stargazers | grep -q '204') ]] && [[ $(curl -s -o /dev/null -w "%{http_code}" https://api.github.com/repos/${{ github.repository }}/forks | grep -q '204') ]]; then
            echo "::set-output name=access::true"
          else
            echo "::set-output name=access::false"
          fi

      - name: Display README content if repository is forked and starred
        if: steps.check-access.outputs.access == 'true'
        run: cat README.md
